/**
 * Entry point for the comment-sync GitHub Action.
 *
 * Modes:
 *   - "poll"  (scheduled): Full bidirectional sync for all mapped pages
 *   - "event" (discussion_comment webhook): Sync a single GH comment → Confluence
 *
 * Page mapping is loaded from a JSON file (generated by the main docs-as-code
 * action) or from an inline JSON string. The file approach is preferred as it
 * keeps the mapping automatically in sync.
 *
 * @module comment-sync/index
 */
import { readFileSync, existsSync } from 'node:fs';
import * as core from '@actions/core';
import ConfluenceSdk from '../confluence-sdk.js';
import GithubClient from './github-client.js';
import PageDiscussionMapping from './mapping.js';
import { syncConfluenceToGithub } from './confluence-to-github.js';
import { batchSyncGithubToConfluence } from './github-to-confluence.js';
import { syncGithubCommentToConfluence } from './github-to-confluence.js';
import { refreshTimestamp } from './discussion-body.js';
import logger from '../logger.js';

async function run() {
    try {
        const mode = core.getInput('mode') || 'poll';
        const requiredInputOptions = { required: true, trimWhitespace: true };
        const optionalInputOptions = { required: false, trimWhitespace: true };

        // ── Confluence configuration ─────────────────────────────────
        const confluenceTenant = core.getInput('confluence_tenant', requiredInputOptions);
        const confluenceHost = `https://${confluenceTenant}.atlassian.net`;
        const confluenceSpace = core.getInput('confluence_space', requiredInputOptions);
        const confluenceSdk = new ConfluenceSdk({
            host: confluenceHost,
            user: core.getInput('confluence_user', requiredInputOptions),
            token: core.getInput('confluence_token', requiredInputOptions),
            spaceKey: confluenceSpace,
            pageLimit: 25
        });

        // ── GitHub configuration ─────────────────────────────────────
        const githubToken = core.getInput('github_token', requiredInputOptions);
        const [owner, repo] = (process.env.GITHUB_REPOSITORY || '').split('/');
        const githubClient = new GithubClient({ token: githubToken, owner, repo });

        // ── Discussion category ──────────────────────────────────────
        const categoryName = core.getInput('discussion_category', requiredInputOptions);
        const categoryId = await githubClient.findCategoryId(categoryName);
        if (!categoryId) {
            core.setFailed(`Discussion category "${categoryName}" not found. Create it in your repo's Discussions settings.`);
            return;
        }

        const mapping = new PageDiscussionMapping(githubClient, categoryId, {
            confluenceHost,
            spaceKey: confluenceSpace
        });

        // ── Page mapping ─────────────────────────────────────────────
        const pages = loadPageMapping();
        if (pages.length === 0) {
            core.setFailed('No valid page mappings found. Provide page_mapping_file (from docs-as-code output) or page_mapping JSON.');
            return;
        }

        const resolvedLabel = core.getInput('resolved_label', optionalInputOptions) || 'resolved';
        const deletedLabel = core.getInput('deleted_label', optionalInputOptions) || 'deleted-on-confluence';

        if (mode === 'poll') {
            logger.info('Running in poll mode — full bidirectional sync');

            // Direction 1: Confluence → GitHub
            const c2gStats = await syncConfluenceToGithub({
                confluenceSdk,
                githubClient,
                mapping,
                pages,
                confluenceHost,
                spaceKey: confluenceSpace,
                resolvedLabel,
                deletedLabel
            });
            logger.info(`[C→GH] Done: ${c2gStats.created} created, ${c2gStats.updated} updated, ${c2gStats.resolved} resolved, ${c2gStats.deleted} deleted`);

            // Direction 2: GitHub → Confluence
            const g2cStats = await batchSyncGithubToConfluence({
                confluenceSdk,
                githubClient,
                mapping,
                pages
            });
            logger.info(`[GH→C] Done: ${g2cStats.created} created, ${g2cStats.updated} updated, ${g2cStats.skipped} skipped`);

            core.setOutput('confluence_to_github', JSON.stringify(c2gStats));
            core.setOutput('github_to_confluence', JSON.stringify(g2cStats));

            // Update "Last synced" timestamp on each Discussion
            const syncTime = new Date();
            for (const { pagePath } of pages) {
                const disc = await mapping.findDiscussion(pagePath);
                if (disc?.body) {
                    const updated = refreshTimestamp(disc.body, syncTime);
                    if (updated !== disc.body) {
                        await githubClient.updateDiscussion(disc.id, updated);
                    }
                }
            }

        } else if (mode === 'event') {
            logger.info('Running in event mode — single comment sync');

            const eventPayload = JSON.parse(process.env.GITHUB_EVENT_PATH
                ? (await import('node:fs')).readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8')
                : '{}');

            const discussionTitle = eventPayload.discussion?.title;
            const comment = eventPayload.comment;

            if (!discussionTitle || !comment) {
                core.setFailed('Event payload missing discussion.title or comment');
                return;
            }

            // Find the Confluence page ID for this Discussion
            const page = pages.find(p => p.pagePath === discussionTitle);
            if (!page) {
                logger.info(`Discussion "${discussionTitle}" is not mapped to a Confluence page, skipping`);
                return;
            }

            const result = await syncGithubCommentToConfluence({
                confluenceSdk,
                comment: { node_id: comment.node_id, body: comment.body },
                pageId: page.pageId
            });

            core.setOutput('sync_result', JSON.stringify(result));
            logger.info(`[GH→C] Result: ${result.action}`);

        } else {
            core.setFailed(`Unknown mode "${mode}". Use "poll" or "event".`);
        }

    } catch (error) {
        core.setFailed(`Comment sync failed: ${error.message}`);
        logger.error(error.stack || error.message);
    }
}

/**
 * Load page mapping from file or inline input.
 *
 * Priority:
 *   1. page_mapping_file input (path to JSON file, e.g. from docs-as-code output)
 *   2. page_mapping input (inline JSON string)
 *
 * The JSON format is: [{pageId: number, pagePath: string, title?: string}, ...]
 *
 * @returns {Array<{pageId: number, pagePath: string}>}
 */
function loadPageMapping() {
    // Priority 1: JSON file (generated by the docs-as-code action)
    const filePath = core.getInput('page_mapping_file', { required: false, trimWhitespace: true });
    if (filePath && existsSync(filePath)) {
        try {
            const data = JSON.parse(readFileSync(filePath, 'utf8'));
            if (Array.isArray(data) && data.length > 0) {
                logger.info(`Loaded ${data.length} page mappings from ${filePath}`);
                return data.map(({ pageId, pagePath }) => ({ pageId: Number(pageId), pagePath }));
            }
        } catch (err) {
            logger.warn(`Failed to read page_mapping_file "${filePath}": ${err.message}`);
        }
    }

    // Priority 2: Inline JSON string
    const inlineJson = core.getInput('page_mapping', { required: false, trimWhitespace: true });
    if (inlineJson) {
        try {
            const data = JSON.parse(inlineJson);
            if (Array.isArray(data) && data.length > 0) {
                logger.info(`Loaded ${data.length} page mappings from inline input`);
                return data.map(({ pageId, pagePath }) => ({ pageId: Number(pageId), pagePath }));
            }
        } catch {
            // Not JSON — this is fine, means no mapping provided
        }
    }

    return [];
}

await run();
